server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '**@**'
    url: jdbc:mysql://localhost:3306/peten?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
      read-timeout: 5s


logging:
  level:
    root: info
    com.douyuehan.doubao: debug